import { GameModeInfo } from './types';

export const GAME_MODES: GameModeInfo[] = [
  {
    type: 'higher',
    name: 'Mayor',
    badge: 'POPULAR',
    description: 'Compara y elige cuál de los 4 futbolistas tiene la estadística más alta. Rápido y letal.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['goals', 'assists', 'market_value', 'appearances', 'champions_league_goals'],
    formats: [4],
  },
  {
    type: 'lower',
    name: 'Menor',
    badge: 'PRECISIÓN',
    description: 'Encuentra al jugador con el registro más bajo en tarjetas, faltas o minutos.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['yellow_cards', 'red_cards', 'appearances'],
    formats: [4],
  },
  {
    type: 'higher-lower',
    name: 'Higher / Lower',
    badge: 'RACHA',
    description: '¿Tiene el siguiente jugador mayor o menor estadística? Mantén la racha viva.',
    defaultRounds: 7,
    defaultTimeLimitSeconds: 12,
    statPool: ['market_value', 'goals', 'assists', 'appearances'],
    formats: [2],
  },
  {
    type: 'exact',
    name: 'Exacto',
    badge: 'EXPERTO',
    description: 'Adivina la cifra exacta de goles o asistencias del futbolista en la temporada.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 20,
    statPool: ['goals', 'assists', 'titles'],
    formats: [1],
  },
  {
    type: 'closest',
    name: 'Más Cercano',
    badge: 'COMPETICIÓN',
    description: 'Aproxima la estadística sin saber el número. Cuanto más cerca, más puntos.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 20,
    statPool: ['market_value', 'minutes', 'goals', 'passes'],
    formats: [1],
  },
  {
    type: 'limit',
    name: 'Límite (Football 21)',
    badge: 'ESTRATEGIA',
    description: 'Selecciona jugadores acumulando estadísticas sin pasarte del tope límite permitido.',
    defaultRounds: 3,
    defaultTimeLimitSeconds: 30,
    statPool: ['goals', 'assists'],
    formats: [6],
  },
  {
    type: 'target',
    name: 'Objetivo',
    badge: 'CÁLCULO',
    description: 'Combina un trío de futbolistas cuya suma de registros alcance exactamente el objetivo marcado.',
    defaultRounds: 3,
    defaultTimeLimitSeconds: 30,
    statPool: ['goals', 'assists'],
    formats: [6],
  },
  {
    type: 'guess-stat',
    name: 'Guess The Stat',
    badge: 'TRIVIA',
    description: 'Se te presenta un futbolista y 4 opciones numéricas plausibles. Elige la correcta.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['goals', 'assists', 'market_value', 'titles'],
    formats: [1],
  },
  {
    type: 'draft',
    name: 'Draft XI',
    badge: 'TÁCTICO',
    description: 'Recluta jugadores posición por posición y construye el equipo con mayor puntuación acumulada.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 45,
    statPool: ['goals', 'assists', 'market_value'],
    formats: [7],
  },
  {
    type: 'squad-dna',
    name: 'Squad DNA',
    badge: 'RADAR',
    description: 'Diseña tu alineación y descubre el ADN de tu plantilla: goles, títulos, valor y veteranía.',
    defaultRounds: 1,
    defaultTimeLimitSeconds: 60,
    statPool: ['goals', 'market_value', 'titles'],
    formats: [11],
  },
  {
    type: 'player-chain',
    name: 'Player Chain',
    badge: 'CONEXIÓN',
    description: 'Encadena futbolistas que compartan club, nacionalidad o competición sin romper el eslabón.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 20,
    statPool: ['appearances'],
    formats: [4],
  },
  {
    type: 'random-challenge',
    name: 'Reto Aleatorio',
    badge: 'SORPRESA',
    description: 'Partida con reglas, formatos, estadísticas y dificultades generadas al azar por el motor.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['goals', 'assists', 'market_value', 'titles'],
    formats: [4],
  },
];
