import { GameModeInfo } from './types';

export const GAME_MODES: GameModeInfo[] = [
  {
    type: 'higher',
    name: 'Mayor',
    badge: 'POPULAR',
    description: 'Elige al futbolista con la estadística más alta. Disponible en 2, 4, 5, 7 u 11 jugadores.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['goals', 'assists', 'market_value', 'appearances', 'champions_league_goals', 'shots_on_target', 'key_passes'],
    formats: [2, 4, 5, 7, 11],
  },
  {
    type: 'lower',
    name: 'Menor',
    badge: 'PRECISIÓN',
    description: 'Encuentra al jugador con el registro más bajo en tarjetas, faltas, minutos o goles.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['yellow_cards', 'red_cards', 'fouls_committed', 'goals_conceded'],
    formats: [2, 4, 5, 7, 11],
  },
  {
    type: 'ranking',
    name: 'Modo Ranking',
    badge: 'ORDEN',
    description: 'Ordena de mayor a menor a un grupo de futbolistas según su registro estadístico real.',
    defaultRounds: 4,
    defaultTimeLimitSeconds: 25,
    statPool: ['goals', 'assists', 'market_value', 'appearances', 'titles'],
    formats: [4, 5],
  },
  {
    type: 'higher-lower',
    name: 'Higher / Lower',
    badge: 'RACHA',
    description: '¿Tiene el siguiente jugador mayor o menor registro? Cada acierto multiplica tu puntuación: x1, x1.2, x1.5, x2, x3...',
    defaultRounds: 7,
    defaultTimeLimitSeconds: 12,
    statPool: ['market_value', 'goals', 'assists', 'appearances', 'shots_on_target'],
    formats: [2],
  },
  {
    type: 'exact',
    name: 'Exacto',
    badge: 'EXPERTO',
    description: 'Adivina la cifra exacta de la estadística. Margen de tolerancia estricto o permisivo según dificultad.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 20,
    statPool: ['goals', 'assists', 'titles', 'penalty_goals', 'clean_sheets'],
    formats: [1],
  },
  {
    type: 'closest',
    name: 'Más Cercano',
    badge: 'COMPETICIÓN',
    description: 'Aproxima la cifra lo más cerca posible del valor real en minutos, pases, tiros o valor de mercado.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 20,
    statPool: ['market_value', 'minutes', 'goals', 'passes', 'shots'],
    formats: [1],
  },
  {
    type: 'limit',
    name: 'Límite (Football 21)',
    badge: 'ESTRATEGIA',
    description: 'Selecciona futbolistas acumulando estadísticas sin sobrepasar el límite fijado. Quien más se acerque sin pasarse, gana.',
    defaultRounds: 3,
    defaultTimeLimitSeconds: 30,
    statPool: ['goals', 'assists', 'market_value', 'titles'],
    formats: [6],
  },
  {
    type: 'target',
    name: 'Target / Objetivo',
    badge: 'CÁLCULO',
    description: 'Alcanza exactamente un número concreto o aproxímate combinando un trío de jugadores.',
    defaultRounds: 3,
    defaultTimeLimitSeconds: 30,
    statPool: ['goals', 'assists', 'titles'],
    formats: [6],
  },
  {
    type: 'guess-stat',
    name: 'Adivina la Estadística',
    badge: 'TRIVIA',
    description: 'Se te revela un número del futbolista y debes deducir qué estadística representa (goles, asistencias, tarjetas o tiros).',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['goals', 'assists', 'yellow_cards', 'shots', 'key_passes'],
    formats: [1],
  },
  {
    type: 'draft',
    name: 'Draft Fantasy XI',
    badge: 'TÁCTICO',
    description: 'Construye un XI equilibrado con formación 1-4-3-3 respetando un presupuesto para maximizar estadísticas.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 45,
    statPool: ['goals', 'assists', 'market_value'],
    formats: [7],
  },
  {
    type: 'squad-dna',
    name: 'Squad DNA',
    badge: 'RADAR',
    description: 'Diseña tu alineación y supera desafíos de plantilla: media de edad < 25, 5+ nacionalidades o récord de goles.',
    defaultRounds: 1,
    defaultTimeLimitSeconds: 60,
    statPool: ['goals', 'market_value', 'titles'],
    formats: [11],
  },
  {
    type: 'player-chain',
    name: 'Player Chain',
    badge: 'CONEXIÓN',
    description: 'Conecta futbolistas que compartan club, selección, o cumplan la condición estadística (el siguiente tiene más goles).',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 20,
    statPool: ['appearances', 'goals', 'market_value'],
    formats: [4],
  },
  {
    type: 'random-challenge',
    name: 'Reto Aleatorio',
    badge: 'SORPRESA',
    description: 'Partida con reglas, formatos, estadísticas y dificultades generadas impredeciblemente por el motor.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['goals', 'assists', 'market_value', 'titles'],
    formats: [4],
  },
  {
    type: 'battle',
    name: '1v1 / Battle',
    badge: 'DUELO',
    description: 'Modo competitivo cara a cara: dos amigos responden a las mismas preguntas para ver quién suma más puntos.',
    defaultRounds: 5,
    defaultTimeLimitSeconds: 15,
    statPool: ['goals', 'assists', 'market_value', 'champions_league_goals'],
    formats: [4],
  },
];
